package github

import (
	"context"
	"fmt"

	"golang.org/x/oauth2"
)

// AuthURL returns the GitHub OAuth authorize URL.
// state should be a random CSRF token generated by the caller.
func (s *Service) AuthURL(state string) (string, error) {
	s.mu.RLock()
	oauthCfg := s.oauth
	s.mu.RUnlock()

	if oauthCfg == nil || oauthCfg.ClientID == "" || oauthCfg.ClientSecret == "" {
		return "", ErrMissingOAuthConfig
	}
	return oauthCfg.AuthCodeURL(state, oauth2.AccessTypeOnline), nil
}

// ExchangeCode exchanges an OAuth authorization code for an access token
// and stores it on the service.
func (s *Service) ExchangeCode(ctx context.Context, code string) error {
	s.mu.RLock()
	oauthCfg := s.oauth
	s.mu.RUnlock()

	if oauthCfg == nil || oauthCfg.ClientID == "" || oauthCfg.ClientSecret == "" {
		return ErrMissingOAuthConfig
	}
	if code == "" {
		return fmt.Errorf("github: empty authorization code")
	}

	token, err := oauthCfg.Exchange(ctx, code)
	if err != nil {
		return fmt.Errorf("github: exchange code: %w", err)
	}
	if token.AccessToken == "" {
		return fmt.Errorf("github: empty access token from exchange")
	}

	return s.SetAccessToken(token.AccessToken)
}

// SetAccessToken authenticates the service with a personal access token
// or an already obtained OAuth access token.
func (s *Service) SetAccessToken(token string) error {
	if token == "" {
		return fmt.Errorf("github: empty access token")
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	s.token = token
	s.client = nil
	return nil
}
