// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function GetOrder(key: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3102688284, key);
}

export function SetOrder(key: string, order: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(495457904, key, order);
}
