// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Clone is a local git repository, optionally matched to a hosting provider.
 */
export interface Clone {
    "provider": string;
    "owner": string;
    "name": string;
    "fullName": string;
    "path": string;
    "htmlUrl": string;
}
