// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Result is the outcome of one dl process.
 */
export interface Result {
    "exitCode": number;
    "stdout": string;
    "stderr": string;
}

/**
 * ServiceState is one dl infrastructure container (traefik, portainer, mail).
 */
export interface ServiceState {
    "name": string;
    "running": boolean;
    "present": boolean;
}

/**
 * Status is the local runtime snapshot for the managed dl binary.
 */
export interface Status {
    "path": string;
    "installed": boolean;
    "version": string;
    "latest": string;
    "updateAvailable": boolean;
    "dockerOk": boolean;
    "dockerVersion": string;
    "dockerOs": string;
    "serviceUp": boolean;
    "services": ServiceState[] | null;
}
