// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActivityEvent is a simplified git host activity event.
 */
export interface ActivityEvent {
    "id": string;
    "type": string;
    "actor": string;
    "repoName": string;
    "repoUrl": string;
    "public": boolean;
    "createdAt": string;
}

/**
 * Branch is a simplified git host branch.
 */
export interface Branch {
    "name": string;
    "sha": string;
    "protected": boolean;
}

/**
 * Commit is a simplified git host commit.
 */
export interface Commit {
    "sha": string;
    "message": string;
    "author": string;
    "avatarUrl": string;
    "htmlUrl": string;
    "date": string;
}

/**
 * ContributionCalendar is a GitHub-style contribution heatmap.
 */
export interface ContributionCalendar {
    "total": number;
    "days": ContributionDay[] | null;
}

/**
 * ContributionDay is one cell of a year-long contribution heatmap.
 */
export interface ContributionDay {
    "date": string;
    "count": number;
    "level": number;
}

/**
 * ListOptions controls pagination.
 */
export interface ListOptions {
    "page": number;
    "perPage": number;
}

/**
 * PageInfo describes pagination metadata.
 */
export interface PageInfo {
    "nextPage": number;
    "prevPage": number;
    "firstPage": number;
    "lastPage": number;
}

/**
 * Provider identifies a git hosting backend.
 */
export enum Provider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProviderUnknown = "",
    ProviderGitHub = "github",
    ProviderGitLab = "gitlab",
};

/**
 * Repository is a simplified git host repository.
 */
export interface Repository {
    "id": number;
    "name": string;
    "fullName": string;
    "description": string;
    "htmlUrl": string;
    "cloneUrl": string;
    "sshUrl": string;
    "defaultBranch": string;
    "language": string;
    "private": boolean;
    "fork": boolean;
    "archived": boolean;
    "stars": number;
    "forks": number;
    "openIssues": number;
    "ownerLogin": string;
    "ownerAvatar": string;
    "pushedAt": string;
    "updatedAt": string;
    "createdAt": string;
}

/**
 * User is a simplified git host profile.
 */
export interface User {
    "id": number;
    "login": string;
    "name": string;
    "email": string;
    "bio": string;
    "company": string;
    "location": string;
    "blog": string;
    "avatarUrl": string;
    "htmlUrl": string;
    "publicRepos": number;
    "followers": number;
    "following": number;
    "createdAt": string;
}
