package github

import (
	"context"
	"fmt"

	"github.com/selyusize/my-home/pkg/git"

	"golang.org/x/oauth2"
)

// AuthURL returns the GitHub OAuth authorize URL.
// state should be a random CSRF token generated by the caller.
func (c *Client) AuthURL(state string) (string, error) {
	c.mu.RLock()
	oauthCfg := c.oauth
	c.mu.RUnlock()

	if oauthCfg == nil || oauthCfg.ClientID == "" || oauthCfg.ClientSecret == "" {
		return "", git.ErrMissingOAuthConfig
	}
	return oauthCfg.AuthCodeURL(state, oauth2.AccessTypeOnline), nil
}

// ExchangeCode exchanges an OAuth authorization code for an access token
// and stores it on the client.
func (c *Client) ExchangeCode(ctx context.Context, code string) error {
	c.mu.RLock()
	oauthCfg := c.oauth
	c.mu.RUnlock()

	if oauthCfg == nil || oauthCfg.ClientID == "" || oauthCfg.ClientSecret == "" {
		return git.ErrMissingOAuthConfig
	}
	if code == "" {
		return fmt.Errorf("github: empty authorization code")
	}

	token, err := oauthCfg.Exchange(ctx, code)
	if err != nil {
		return fmt.Errorf("github: exchange code: %w", err)
	}
	if token.AccessToken == "" {
		return fmt.Errorf("github: empty access token from exchange")
	}

	return c.SetAccessToken(token.AccessToken)
}

// SetAccessToken authenticates the client with a personal access token
// or an already obtained OAuth access token.
func (c *Client) SetAccessToken(token string) error {
	if token == "" {
		return fmt.Errorf("github: empty access token")
	}

	c.mu.Lock()
	defer c.mu.Unlock()
	c.token = token
	c.client = nil
	return nil
}
