// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitHubService exposes the GitHub API to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as github$0 from "../../pkg/github/models.js";

/**
 * AccessToken returns the current access token.
 */
export function AccessToken(): $CancellablePromise<string> {
    return $Call.ByID(1376789528);
}

/**
 * AuthURL returns the GitHub OAuth authorize URL.
 * state should be a random CSRF token generated by the caller.
 */
export function AuthURL(state: string): $CancellablePromise<string> {
    return $Call.ByID(1661798264, state);
}

/**
 * ExchangeCode exchanges an OAuth authorization code for an access token
 * and stores it on the service.
 */
export function ExchangeCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(3026438053, code);
}

/**
 * GetProfile returns the authenticated user's profile.
 */
export function GetProfile(): $CancellablePromise<github$0.User | null> {
    return $Call.ByID(3683934616);
}

/**
 * GetRepository returns repository details by owner and name.
 */
export function GetRepository(owner: string, name: string): $CancellablePromise<github$0.Repository | null> {
    return $Call.ByID(2755659211, owner, name);
}

/**
 * GetUser returns a public profile by login.
 */
export function GetUser(login: string): $CancellablePromise<github$0.User | null> {
    return $Call.ByID(3197943892, login);
}

/**
 * IsAuthenticated reports whether an access token is set.
 */
export function IsAuthenticated(): $CancellablePromise<boolean> {
    return $Call.ByID(2545966200);
}

/**
 * ListRepos returns repositories for the authenticated user.
 */
export function ListRepos(opts: github$0.ListOptions): $CancellablePromise<[github$0.Repository[] | null, github$0.PageInfo]> {
    return $Call.ByID(4035244766, opts);
}

/**
 * ListRepositoryActivity returns events for a repository.
 */
export function ListRepositoryActivity(owner: string, name: string, opts: github$0.ListOptions): $CancellablePromise<[github$0.ActivityEvent[] | null, github$0.PageInfo]> {
    return $Call.ByID(2422826960, owner, name, opts);
}

/**
 * ListUserActivity returns events performed by the authenticated user.
 * If login is empty, the authenticated profile login is used.
 */
export function ListUserActivity(login: string, opts: github$0.ListOptions): $CancellablePromise<[github$0.ActivityEvent[] | null, github$0.PageInfo]> {
    return $Call.ByID(1738511299, login, opts);
}

/**
 * Logout clears the current session.
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(2767792155);
}

/**
 * SetAccessToken authenticates the service with a personal access token
 * or an already obtained OAuth access token.
 */
export function SetAccessToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(2197258622, token);
}
