// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Container is a simplified container list item.
 */
export interface Container {
    "id": string;
    "name": string;
    "names": string[] | null;
    "image": string;
    "imageId": string;
    "command": string;
    "state": string;
    "status": string;
    "ports": Port[] | null;
    "labels": { [_ in string]?: string } | null;
    "created": string;
}

/**
 * ContainerDetails is a simplified inspect result.
 */
export interface ContainerDetails {
    "id": string;
    "name": string;
    "names": string[] | null;
    "image": string;
    "imageId": string;
    "command": string;
    "state": string;
    "status": string;
    "ports": Port[] | null;
    "labels": { [_ in string]?: string } | null;
    "created": string;
    "path": string;
    "args": string[] | null;
    "platform": string;
    "restartCount": number;
    "pid": number;
    "exitCode": number;
    "startedAt": string;
    "finishedAt": string;
}

/**
 * ContainerListOptions controls which containers are returned.
 */
export interface ContainerListOptions {
    "all": boolean;
    "limit": number;
}

/**
 * ContainerRemoveOptions controls container deletion.
 */
export interface ContainerRemoveOptions {
    "force": boolean;
    "removeVolumes": boolean;
}

/**
 * Image is a simplified image list item.
 */
export interface Image {
    "id": string;
    "repoTags": string[] | null;
    "repoDigests": string[] | null;
    "labels": { [_ in string]?: string } | null;
    "size": number;
    "containers": number;
    "created": string;
}

/**
 * ImageDetails is a simplified image inspect result.
 */
export interface ImageDetails {
    "id": string;
    "repoTags": string[] | null;
    "repoDigests": string[] | null;
    "labels": { [_ in string]?: string } | null;
    "size": number;
    "containers": number;
    "created": string;
    "author": string;
    "comment": string;
    "architecture": string;
    "os": string;
}

/**
 * Info is a simplified docker daemon summary.
 */
export interface Info {
    "id": string;
    "name": string;
    "serverVersion": string;
    "operatingSystem": string;
    "osVersion": string;
    "osType": string;
    "architecture": string;
    "ncpu": number;
    "memTotal": number;
    "driver": string;
    "dockerRootDir": string;
    "containers": number;
    "containersRunning": number;
    "containersPaused": number;
    "containersStopped": number;
    "images": number;
}

/**
 * Network is a simplified docker network.
 */
export interface Network {
    "id": string;
    "name": string;
    "driver": string;
    "scope": string;
    "internal": boolean;
    "created": string;
}

/**
 * Ping is a lightweight daemon health check.
 */
export interface Ping {
    "apiVersion": string;
    "osType": string;
    "experimental": boolean;
}

/**
 * Port is a published container port.
 */
export interface Port {
    "ip": string;
    "privatePort": number;
    "publicPort": number;
    "type": string;
}

/**
 * Provider identifies a container engine backend.
 */
export enum Provider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProviderUnknown = "",
    ProviderEngine = "engine",
};

/**
 * StopOptions controls graceful stop/restart timeout.
 */
export interface StopOptions {
    "timeout": number | null;
}

/**
 * Volume is a simplified named volume.
 */
export interface Volume {
    "name": string;
    "driver": string;
    "mountpoint": string;
    "scope": string;
    "labels": { [_ in string]?: string } | null;
    "createdAt": string;
}
