// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as docker$0 from "../../pkg/docker/models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(130094570);
}

export function Info(): $CancellablePromise<docker$0.Info | null> {
    return $Call.ByID(843182718);
}

export function InspectContainer(id: string): $CancellablePromise<docker$0.ContainerDetails | null> {
    return $Call.ByID(3506642401, id);
}

export function InspectImage(id: string): $CancellablePromise<docker$0.ImageDetails | null> {
    return $Call.ByID(2772480903, id);
}

export function ListContainers(opts: docker$0.ContainerListOptions): $CancellablePromise<docker$0.Container[] | null> {
    return $Call.ByID(1780004606, opts);
}

export function ListImages(all: boolean): $CancellablePromise<docker$0.Image[] | null> {
    return $Call.ByID(970694628, all);
}

export function ListNetworks(): $CancellablePromise<docker$0.Network[] | null> {
    return $Call.ByID(464711073);
}

export function ListVolumes(): $CancellablePromise<docker$0.Volume[] | null> {
    return $Call.ByID(642445693);
}

export function Ping(): $CancellablePromise<docker$0.Ping | null> {
    return $Call.ByID(1888824886);
}

export function Provider(): $CancellablePromise<docker$0.Provider> {
    return $Call.ByID(2922324475);
}

export function RemoveContainer(id: string, opts: docker$0.ContainerRemoveOptions): $CancellablePromise<void> {
    return $Call.ByID(1595555945, id, opts);
}

export function RemoveImage(id: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(4123997615, id, force);
}

export function RestartContainer(id: string, opts: docker$0.StopOptions): $CancellablePromise<void> {
    return $Call.ByID(644996, id, opts);
}

export function StartContainer(id: string): $CancellablePromise<void> {
    return $Call.ByID(1282008797, id);
}

export function StopContainer(id: string, opts: docker$0.StopOptions): $CancellablePromise<void> {
    return $Call.ByID(1718098869, id, opts);
}
