// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../pkg/git/models.js";

export function AccessToken(): $CancellablePromise<string> {
    return $Call.ByID(901977082);
}

export function AuthURL(state: string): $CancellablePromise<string> {
    return $Call.ByID(1584857098, state);
}

export function ContributionCalendar(): $CancellablePromise<git$0.ContributionCalendar | null> {
    return $Call.ByID(750951471);
}

export function ExchangeCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(19681611, code);
}

export function IsAuthenticated(): $CancellablePromise<boolean> {
    return $Call.ByID(1274340994);
}

export function ListBranches(owner: string, name: string, opts: git$0.ListOptions): $CancellablePromise<[git$0.Branch[] | null, git$0.PageInfo]> {
    return $Call.ByID(3293515199, owner, name, opts);
}

export function ListCommits(owner: string, name: string, ref: string, opts: git$0.ListOptions): $CancellablePromise<[git$0.Commit[] | null, git$0.PageInfo]> {
    return $Call.ByID(1891184567, owner, name, ref, opts);
}

export function ListRepos(opts: git$0.ListOptions): $CancellablePromise<[git$0.Repository[] | null, git$0.PageInfo]> {
    return $Call.ByID(1128181252, opts);
}

export function ListRepositoryActivity(owner: string, name: string, opts: git$0.ListOptions): $CancellablePromise<[git$0.ActivityEvent[] | null, git$0.PageInfo]> {
    return $Call.ByID(823313490, owner, name, opts);
}

export function ListUserActivity(login: string, opts: git$0.ListOptions): $CancellablePromise<[git$0.ActivityEvent[] | null, git$0.PageInfo]> {
    return $Call.ByID(2710127049, login, opts);
}

export function Login(): $CancellablePromise<git$0.User | null> {
    return $Call.ByID(3403927796);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(1823936161);
}

export function Profile(): $CancellablePromise<git$0.User | null> {
    return $Call.ByID(446569712);
}

export function Provider(): $CancellablePromise<git$0.Provider> {
    return $Call.ByID(1731508526);
}

export function Repository(owner: string, name: string): $CancellablePromise<git$0.Repository | null> {
    return $Call.ByID(891235, owner, name);
}

export function SetAccessToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(1941565992, token);
}

export function User(login: string): $CancellablePromise<git$0.User | null> {
    return $Call.ByID(1145672364, login);
}
