// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as GitHubService from "./githubservice.js";
import * as GitLabService from "./gitlabservice.js";
import * as LocalReposService from "./localreposservice.js";
export {
    GitHubService,
    GitLabService,
    LocalReposService
};

export type {
    LocalRepoSettings,
    ScanReport
} from "./models.js";
