// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalReposService stores local clone folders and scan results.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as local$0 from "../../pkg/git/local/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Check(settings: $models.LocalRepoSettings): $CancellablePromise<$models.ScanReport> {
    return $Call.ByID(106674796, settings);
}

export function GetSettings(): $CancellablePromise<$models.LocalRepoSettings> {
    return $Call.ByID(3270875757);
}

export function ListClones(provider: string): $CancellablePromise<local$0.Clone[] | null> {
    return $Call.ByID(1303676918, provider);
}

export function SaveSettings(settings: $models.LocalRepoSettings): $CancellablePromise<void> {
    return $Call.ByID(4161877100, settings);
}

export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(1422469831, title);
}
