// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalRepoSettings is the persisted folder configuration from the profile page.
 */
export interface LocalRepoSettings {
    "sharedPath": string;
    "githubSeparate": boolean;
    "githubPath": string;
    "gitlabSeparate": boolean;
    "gitlabPath": string;
}

/**
 * ScanReport is how many clones Check stored per provider.
 */
export interface ScanReport {
    "github": number;
    "gitlab": number;
}
