// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bitrix$0 from "../../pkg/bitrix/models.js";

export function IsAuthenticated(): $CancellablePromise<boolean> {
    return $Call.ByID(2246045581);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(2997830204);
}

export function Profile(): $CancellablePromise<bitrix$0.Profile | null> {
    return $Call.ByID(144497679);
}

export function SetWebhook(domain: string, webhook: string): $CancellablePromise<bitrix$0.Profile | null> {
    return $Call.ByID(3910332627, domain, webhook);
}

export function TimeMan(): $CancellablePromise<bitrix$0.TimeMan | null> {
    return $Call.ByID(3538381501);
}

export function TimeManClose(): $CancellablePromise<void> {
    return $Call.ByID(613890347);
}

export function TimeManOpen(): $CancellablePromise<void> {
    return $Call.ByID(343404481);
}

export function TimeManPause(): $CancellablePromise<void> {
    return $Call.ByID(3688118997);
}
