// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActivityEvent is a simplified GitHub activity event.
 */
export interface ActivityEvent {
    "id": string;
    "type": string;
    "actor": string;
    "repoName": string;
    "repoUrl": string;
    "public": boolean;
    "createdAt": string;
}

/**
 * ListOptions controls pagination.
 */
export interface ListOptions {
    "page": number;
    "perPage": number;
}

/**
 * PageInfo describes pagination metadata.
 */
export interface PageInfo {
    "nextPage": number;
    "prevPage": number;
    "firstPage": number;
    "lastPage": number;
}

/**
 * Repository is a simplified GitHub repository.
 */
export interface Repository {
    "id": number;
    "name": string;
    "fullName": string;
    "description": string;
    "htmlUrl": string;
    "cloneUrl": string;
    "sshUrl": string;
    "defaultBranch": string;
    "language": string;
    "private": boolean;
    "fork": boolean;
    "archived": boolean;
    "stars": number;
    "forks": number;
    "openIssues": number;
    "ownerLogin": string;
    "ownerAvatar": string;
    "pushedAt": string;
    "updatedAt": string;
    "createdAt": string;
}

/**
 * User is a simplified GitHub profile.
 */
export interface User {
    "id": number;
    "login": string;
    "name": string;
    "email": string;
    "bio": string;
    "company": string;
    "location": string;
    "blog": string;
    "avatarUrl": string;
    "htmlUrl": string;
    "publicRepos": number;
    "followers": number;
    "following": number;
    "createdAt": string;
}
