// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dl$0 from "../../pkg/dl/models.js";

export function Exec(workdir: string, args: string[] | null): $CancellablePromise<dl$0.Result | null> {
    return $Call.ByID(3751209059, workdir, args);
}

export function Install(): $CancellablePromise<void> {
    return $Call.ByID(2611632045);
}

export function ServiceDown(): $CancellablePromise<void> {
    return $Call.ByID(513866493);
}

export function ServiceUp(): $CancellablePromise<void> {
    return $Call.ByID(2486001608);
}

export function Status(): $CancellablePromise<dl$0.Status | null> {
    return $Call.ByID(835952664);
}

export function Uninstall(): $CancellablePromise<void> {
    return $Call.ByID(2529101040);
}
