// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Profile is the current Bitrix24 user.
 */
export interface Profile {
    "id": number;
    "name": string;
    "email": string;
    "position": string;
    "avatarUrl": string;
    "portalUrl": string;
    "pageUrl": string;
}

/**
 * TimeMan is the current workday snapshot.
 */
export interface TimeMan {
    "status": TimeManStatus;
    "timeStart": string;
    "duration": number;
    "timeLeaks": number;
}

/**
 * TimeManStatus is the workday state from timeman.status.
 */
export enum TimeManStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TimeManUnknown = "",
    TimeManOpened = "opened",
    TimeManPaused = "paused",
    TimeManClosed = "closed",
    TimeManExpired = "expired",
};
